{% set name = "types-editdistance" %}
{% set version = "0.8.0.20240421" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-editdistance-{{ version }}.tar.gz
  sha256: f20f6c319887e3655fb898522e1eebc6c18562ef87fb8116c98601a80188a5c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/editdistance-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\editdistance-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for editdistance
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxvolk
